logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    org.springframework.security: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: ERROR
    org.springframework.cache: ERROR
spring:
  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jmx:
    default-domain: gifts
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <ID>
            clientSecret: <SECRET>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: <ID>
            clientSecret: <SECRET>
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
# See db/application.yml" properties of what have to be set
#  mail:
#    host: localhost
#    port: 25
#    protocol: smtp
#    from: gifts-hub@q-programming.pl
#  datasource:
#    #    url: jdbc:h2:./db/h2databaseFile;AUTO_SERVER=TRUE
#    #    username: sa
#    #    password:
#    url: jdbc:postgresql://localhost:5432/gifts
#    username: giftshub
#    password: 3olQQV7rPLXYqSQYQGWP
#  social:
#    facebook:
#      app-id: 1750703375258695
#      app-secret: fb3c3e7ed3b5ffa7db0586c659198424
#server:
#  port: 8080
#app:
#  name: Gifts hub
#  gift:
#    age: 30
#  newsletter:
#    schedule: 0 0 20 * * MON
#
#security:
#  #  user:
#  #    password: password
#  oauth2:
#    client:
#      client-id: gifts-hub
#      client-secret: w42sPRPzcbe9HEupuqC4meXjxxnetwTtEYrcAAja
#      scope: read,write
#      auto-approve-scopes: '.*'
#    resource:
#      userInfoUri: "*"
#facebook:
#  client:
#    clientId: 1750703375258695
#    clientSecret: fb3c3e7ed3b5ffa7db0586c659198424
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=email,name,locale
#google:
#  client:
#    clientId: 147965203195-249cgo1f756ral9h3j5ra8g1oaimffkg.apps.googleusercontent.com
#    clientSecret: mjOKZ9PiJyumDUyXqL2mLtRa
#    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#    clientAuthenticationScheme: form
#    scope:
#      - openid
#      - email
#      - profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#    preferTokenInfo: true
#jwt:
#  header: Authorization
#  expires_in: 604800 # week
#  secret: f4CKnPY3bt87c68mQFFAZWSGfW8ZUuf7YWqcYqX5t9EedppMEU
#  cookie: COOKIE-AUTH-TOKEN
#  xsrf: XSRF-TOKEN
#  jsessionid: JSESSIONID
#  user_cookie: c_user
