server:
  port: 8080
#  context-path: /gifts
app:
  name: Gifts hub
  gift:
    age: 30
  newsletter:
    schedule: 0 0 10-12 * * MON
security:
#  user:
#    password: password
  oauth2:
      client:
        client-id: gifts-hub
        client-secret: w42sPRPzcbe9HEupuqC4meXjxxnetwTtEYrcAAja
        scope: read,write
        auto-approve-scopes: '.*'
logging:
  level:
    org.springframework.security: ERROR
spring:
  mail:
    host: localhost
    port: 25
    protocol: smtp
    from: gifts-hub@q-programming.pl
  datasource:
    url: jdbc:h2:./db/h2databaseFile;AUTO_SERVER=TRUE
    username: sa
    password:
#    url: jdbc:postgresql://localhost:5432/gifts
#    username: giftshub
#    password: h9fj67kmZ9FyU75ndwZU
  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
  social:
    facebook:
      app-id: 1750703375258695
      app-secret: fb3c3e7ed3b5ffa7db0586c659198424
facebook:
  client:
    clientId: 1750703375258695
    clientSecret: fb3c3e7ed3b5ffa7db0586c659198424
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
google:
  client:
    clientId: 147965203195-249cgo1f756ral9h3j5ra8g1oaimffkg.apps.googleusercontent.com
    clientSecret: mjOKZ9PiJyumDUyXqL2mLtRa
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
      - openid
      - email
      - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
    preferTokenInfo: true
jwt:
  header: Authorization
  expires_in: 604800 # week
  secret: f4CKnPY3bt87c68mQFFAZWSGfW8ZUuf7YWqcYqX5t9EedppMEU
  cookie: AUTH-TOKEN
  user_cookie: c_user