version: 2.1
jobs:
  build:
    docker:
      - image: khobar/docker-jdk-8-maven-node-ng
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Build application
          command: mvn clean install -DskipTests=true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /root/repo
          paths:
            - .
  test:
    docker:
      - image: khobar/docker-jdk-8-maven-node-ng
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: /root/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Test
          command: mvn integration-test
      - store_artifacts:
          path: /root/repo/gifts-app/target/gifts.war
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - persist_to_workspace:
          root: /root/repo
          paths:
            - .
  deploy:
    docker:
      - image: khobar/docker-jdk-8-maven-node-ng
    working_directory: ~/repo
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /root/repo
      - store_artifacts:
          path: /root/repo/gifts-app/target/gifts.war

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
