spring:

  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jmx:
    default-domain: gifts
  main:
    allow-bean-definition-overriding: true
  mail:
    host: localhost
    port: 25
    protocol: smtp
    from: gifts-hub@q-programming.pl
  datasource:
    #    url: jdbc:h2:./db/h2databaseFile;AUTO_SERVER=TRUE
    #    username: sa
    #    password:
    url: jdbc:postgresql://192.168.1.50:5432/gifts
    username: postgres
    password: password
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 147965203195-249cgo1f756ral9h3j5ra8g1oaimffkg.apps.googleusercontent.com
            clientSecret: WCvRNnJEGwssJmjk1itF8m6v
          facebook:
            clientId: 1750703375258695
            clientSecret: <SECRET>
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v15.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v15.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v15.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
server:
  port: 8080
  servlet:
    context-path: /gifts
app:
  name: Gifts hub
  birthday-reminder: 14
  gift:
    age: 30
  newsletter:
    schedule: 0 0 20 * * MON
    birthday: 0 3 22 * * *

jwt:
  header: Authorization
  expires_in: 604800
  secret: f4CKnPY3bt87c68mQFFAZWSGfW8ZUuf7YWqcYqX5t9EedppMEU
  cookie: COOKIE-AUTH-TOKEN
  xsrf: XSRF-TOKEN
  jsessionid: JSESSIONID
  user_cookie: c_user
