name: Build , Test and Publish
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache setup
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Angular-CLI
        run: npm install --unsafe-perm -g @angular/cli

      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean package

      - name: Store artefact
        uses: actions/upload-artifact@v4
        with:
          name: gifts.war
          path: gifts-app/target/gifts.war

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload to release
        if: github.event_name == 'release' && github.event.action == 'created'
        uses: JasonEtco/upload-to-release@master
        with:
          args: gifts-app/target/gifts.war application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}